package DictionaryMark {
    part def DictionaryGenerator {
        doc /* Orchestrates dictionary generation. */

        comment sourceRef /* Source: src/DemaConsulting.DictionaryMark/Dictionary/DictionaryGenerator.cs */
        comment testRef /* Test: test/DemaConsulting.DictionaryMark.Tests/Dictionary/DictionaryGeneratorTests.cs */
        comment designRef /* Design: docs/design/dictionary-mark/dictionary/dictionary-generator.md */
        comment verificationRef /* Verification: docs/verification/dictionary-mark/dictionary/dictionary-generator.md */
        comment reqRef /* Requirements: docs/reqstream/dictionary-mark/dictionary/dictionary-generator.yaml */
    }
}
