---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/demaconsulting/DictionaryMark
    about: Read the documentation for DictionaryMark
  - name: 💬 Discussions
    url: https://github.com/demaconsulting/DictionaryMark/discussions
    about: Ask questions and discuss with the community
