package DictionaryMark {
    part def GlobMatcher {
        doc /* File-matching via glob patterns. */

        comment sourceRef /* Source: src/DemaConsulting.DictionaryMark/Utilities/GlobMatcher.cs */
        comment testRef /* Test: test/DemaConsulting.DictionaryMark.Tests/Utilities/GlobMatcherTests.cs */
        comment designRef /* Design: docs/design/dictionary-mark/utilities/glob-matcher.md */
        comment verificationRef /* Verification: docs/verification/dictionary-mark/utilities/glob-matcher.md */
        comment reqRef /* Requirements: docs/reqstream/dictionary-mark/utilities/glob-matcher.yaml */
    }
}
