package DictionaryMark {
    part def Validation {
        doc /* Self-validation test runner. */

        comment sourceRef /* Source: src/DemaConsulting.DictionaryMark/SelfTest/Validation.cs */
        comment testRef /* Test: test/DemaConsulting.DictionaryMark.Tests/SelfTest/ValidationTests.cs */
        comment designRef /* Design: docs/design/dictionary-mark/self-test/validation.md */
        comment verificationRef /* Verification: docs/verification/dictionary-mark/self-test/validation.md */
        comment reqRef /* Requirements: docs/reqstream/dictionary-mark/self-test/validation.yaml */
    }
}
